### ISSUE TITLE
No Way to Turn Off Notifications

### ISSUE THREAD

**Issue by 15rtrujillo** [RSCPlus/rsctimes#20]
Currently it seems that _all_ system notifications are defaulted to on and I cannot find a way to turn them off. It's pretty annoying to play on RSCx when you're getting blasted with the Windows notification sound all the time. I'm sure this will get better as people fall off the game, but there should probably be a way to turn these off or have them off by default.

**Comment by conker-rsc** [comment]
This has been resolved with https://github.com/RSCPlus/rsctimes/pull/28
